name: klaviyo_example
description: Demonstrates how to use the klaviyo_flutter plugin.
publish_to: none

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  klaviyo_flutter:
    path: ../

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.18.0 <3.0.0"
